name: Lint
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: bahmutov/npm-install@v1
      - name: awesome-lint
        run: yarn test --color
